# Generated by Django 3.0.3 on 2020-04-03 11:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other',
            name='reg_time',
            field=models.DateField(default=datetime.datetime(2020, 4, 3, 11, 59, 15, 26566, tzinfo=utc)),
        ),
    ]
