# Generated by Django 3.0.3 on 2020-03-26 04:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='graph_device',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='reg_time',
            field=models.DateField(default=datetime.datetime(2020, 3, 26, 4, 56, 19, 809120, tzinfo=utc)),
        ),
    ]
