# Generated by Django 3.0.3 on 2020-04-03 11:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0003_auto_20200328_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='reg_time',
            field=models.DateField(default=datetime.datetime(2020, 4, 3, 11, 59, 15, 25241, tzinfo=utc)),
        ),
    ]
