# Generated by Django 2.2.7 on 2020-06-05 08:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0007_auto_20200526_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='reg_time',
            field=models.DateField(default=datetime.datetime(2020, 6, 5, 8, 4, 14, 376133, tzinfo=utc)),
        ),
    ]
