# Generated by Django 3.0.3 on 2020-03-05 07:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userPassword',
        ),
        migrations.AddField(
            model_name='user',
            name='address_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='xxx@xxx.com', max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='group_id',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_time',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='reg_time',
            field=models.DateField(default=datetime.datetime(2020, 3, 5, 7, 34, 56, 543903, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='user',
            name='small_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='小明', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='user_password',
            field=models.CharField(default='123456', max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='user_rename',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_repassword',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_school',
            field=models.CharField(default='SWPU', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='usercomment_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='userlikecomment_id',
            field=models.IntegerField(null=True),
        ),
    ]
