# Generated by Django 3.0.3 on 2020-03-13 06:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField(default=2)),
                ('usercomment_id', models.IntegerField(null=True)),
                ('address_id', models.IntegerField(null=True)),
                ('user_name', models.CharField(default='小明', max_length=20)),
                ('user_password', models.CharField(default='123456', max_length=256)),
                ('email', models.EmailField(default='xxx@xxx.com', max_length=254)),
                ('user_school', models.CharField(default='SWPU', max_length=20)),
                ('pic', models.ImageField(null=True, upload_to='')),
                ('small_pic', models.ImageField(null=True, upload_to='')),
                ('reg_time', models.DateField(default=datetime.datetime(2020, 3, 13, 6, 31, 33, 903988, tzinfo=utc))),
                ('last_login_time', models.DateField(auto_now=True)),
                ('userlikecomment_id', models.IntegerField(null=True)),
                ('user_rename', models.CharField(max_length=20, null=True)),
                ('user_repassword', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
