# Generated by Django 3.0.3 on 2020-03-25 03:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('graph_name', models.CharField(max_length=20)),
                ('user_school', models.CharField(max_length=20)),
                ('graph_school', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='photographer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graphcomment_id', models.IntegerField(null=True)),
                ('group_id', models.IntegerField(default=1)),
                ('graph_name', models.CharField(default='ssa', max_length=20)),
                ('graph_password', models.CharField(default='23456', max_length=256)),
                ('graph_school', models.CharField(default='pku', max_length=20)),
                ('email', models.EmailField(default='xxx@xxx.com', max_length=254)),
                ('graph_identification', models.CharField(max_length=18)),
                ('experience', models.CharField(max_length=1000)),
                ('album', models.ImageField(upload_to='')),
                ('pic', models.ImageField(null=True, upload_to='')),
                ('small_pic', models.ImageField(null=True, upload_to='')),
                ('reg_time', models.DateField(default=datetime.datetime(2020, 3, 25, 3, 41, 59, 504102, tzinfo=utc))),
                ('last_login_time', models.DateField(auto_now=True)),
                ('graphlikecomment_id', models.IntegerField(null=True)),
                ('graph_rename', models.CharField(max_length=20, null=True)),
                ('graph_repassword', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='reg_time',
            field=models.DateField(default=datetime.datetime(2020, 3, 25, 3, 41, 59, 502476, tzinfo=utc)),
        ),
    ]
