# Generated by Django 3.0.3 on 2020-03-26 04:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200325_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='reg_time',
            field=models.DateField(default=datetime.datetime(2020, 3, 26, 4, 56, 19, 803101, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='reg_time',
            field=models.DateField(default=datetime.datetime(2020, 3, 26, 4, 56, 19, 801439, tzinfo=utc)),
        ),
    ]
