# Generated by Django 3.0.3 on 2020-03-28 09:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200326_0456'),
    ]

    operations = [
        migrations.DeleteModel(
            name='photographer',
        ),
        migrations.AlterField(
            model_name='user',
            name='reg_time',
            field=models.DateField(default=datetime.datetime(2020, 3, 28, 9, 13, 33, 254351, tzinfo=utc)),
        ),
    ]
