# Generated by Django 3.0.3 on 2020-04-08 05:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200403_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment_content',
            field=models.CharField(default='null', max_length=144),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='reg_time',
            field=models.DateField(default=datetime.datetime(2020, 4, 8, 5, 54, 10, 376612, tzinfo=utc)),
        ),
    ]
