# Generated by Django 3.0.3 on 2020-04-08 07:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200408_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='comments',
            name='graph_school',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='reg_time',
            field=models.DateField(default=datetime.datetime(2020, 4, 8, 7, 2, 36, 30398, tzinfo=utc)),
        ),
    ]
