# Generated by Django 3.0.3 on 2020-05-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200408_0702'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('graph_name', models.CharField(max_length=20)),
                ('order_time', models.DateField(auto_now_add=True)),
                ('total', models.IntegerField(max_length=10)),
                ('update_time', models.DateField(auto_now=True)),
                ('order_status', models.BooleanField(default=False)),
                ('payment_status', models.BooleanField(default=False)),
                ('meet_time', models.DateField()),
                ('address', models.CharField(max_length=256)),
                ('tel', models.CharField(max_length=11)),
                ('user_school', models.CharField(max_length=20)),
                ('graph_school', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='reg_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
