# Generated by Django 2.2.7 on 2020-06-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200526_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='forget_code',
            field=models.CharField(default='a73Uv', max_length=5),
        ),
    ]
