# Generated by Django 2.2.7 on 2020-08-08 08:15

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_forget_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='verify_code',
            field=models.CharField(default=user.models.make_verify_code, max_length=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='forget_code',
            field=models.CharField(default=user.models.make_forget_code, max_length=5),
        ),
    ]
